---
all:
  hosts:
    student_machine:
      ansible_host: 127.0.0.1
      ansible_connection: local
  children:
    aws_hosts:
      vars:
        ansible_python_interpreter: "/usr/bin/python3"
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
