---
- name: Install apt dependencies
  package:
    name:
      - python3-pip
    state: latest
    update_cache: yes

# This is separate from the pip task that follows to limit
# potential for a deadlock on CPU-limited EC2 instances
- name: Install pip dependencies
  become: false
  pip:
    name: "ansible=={{ ansible_vers }}"

# Install as the unprivileged ubuntu user on the EC2 instance
- name: Install BBOT Python module
  tags: point
  become: false
  pip:
    name: "bbot"

# This ensures that Python will know where to find the bbot module
# The output module will later call BBOT functions in order to create the secrets.yml file on the EC2 instance
# PYTHONPATH is used to locate the BBOT module
- name: Export "PYTHONPATH"
  become: false
  lineinfile:
    dest: /home/ubuntu/.bashrc
    line: "export PYTHONPATH={{ python_path }}"
  
