---
# This will allow the student to more easily execute ansible in the event they need to
# re-run all or part of the playbook
- name: "Update PATH for Ansible"
  become: false
  lineinfile:
    dest: /home/{{ ansible_user_id }}/.bashrc
    line: "export PATH={{ ansible_path }}:$PATH"